# Generated by Django 2.1.4 on 2019-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(verbose_name='Fecha evento')),
                ('categoria', models.CharField(choices=[('G', 'Generales'), ('A', 'Autonomicas'), ('L', 'Locales')], max_length=1)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField()),
                ('municipio', models.CharField(max_length=30)),
                ('domicilio', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('mesa', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('dni',),
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='votantes',
            field=models.ManyToManyField(blank=True, default=None, to='votaciones.Usuario'),
        ),
    ]
